# Travis CI for automatic building.
#
# Changelog:
#   2017-09-19: Updated to native R building.

language: r
cache: packages
sudo: false

matrix:
  include:
  - env: BUILD_NLOPT=no
  - env: BUILD_NLOPT=yes
    addons:
      apt:
        packages:
          - libnlopt-dev
 
 after_failure:
  - cat /home/travis/build/jyypma/nloptr/nloptr.Rcheck/00check.logs

notifications:
  email:
    on_success: change
    on_failure: change
