# Travis CI for automatic building.
#
# Changelog:
#   2017-09-19: Updated to native R building.

language: r
cache: packages
sudo: false

matrix:
  include:
  - env: BUILD_NLOPT=yes
  - env: BUILD_NLOPT=no
    addons:
      apt:
        packages:
          - libnlopt-dev

after_success:
  - cat /home/travis/build/jyypma/nloptr/nloptr.Rcheck/00check.log
  - cat /home/travis/build/jyypma/nloptr/nloptr.Rcheck/00install.out

after_failure:
  - cat /home/travis/build/jyypma/nloptr/nloptr.Rcheck/00check.log
  - cat /home/travis/build/jyypma/nloptr/nloptr.Rcheck/00install.out
  
notifications:
  email:
    on_success: change
    on_failure: change
